import re
import urllib.request
import json
from langchain_ollama import ChatOllama
from langchain_core.messages import SystemMessage, HumanMessage

def get_local_ollama_models() -> list:
    """
    Queries the local Ollama API to get a list of installed models.
    """
    try:
        req = urllib.request.Request("http://localhost:11434/api/tags")
        with urllib.request.urlopen(req, timeout=2) as response:
            data = json.loads(response.read().decode("utf-8"))
            models = [m["name"] for m in data.get("models", [])]
            models = [m for m in models if "embed" not in m.lower()]
            return models
    except Exception:
        return ["mistral:latest", "llama3:latest", "llama3.1:8b", "llama2:latest"]

def set_current_model(model_name: str):
    """
    Updates the global LLM instance to use the specified model.
    """
    global llm
    llm = ChatOllama(model=model_name, streaming=True)

# Select initial model
_models = get_local_ollama_models()
_initial_model = "mistral:latest"
if _initial_model not in _models:
    _mistral_vars = [m for m in _models if "mistral" in m.lower()]
    if _mistral_vars:
        _initial_model = _mistral_vars[0]
    elif _models:
        _initial_model = _models[0]

llm = ChatOllama(model=_initial_model, streaming=True)


def _fix_formatting(text: str) -> str:
    """
    Normalises LLM output so it renders cleanly in Streamlit markdown:
    - Converts bullet chars (bullet, middot) to markdown '- '
    - Splits inline bullets onto their own lines
    - Adds blank line before bold section headers
    - Collapses excessive blank lines
    """
    # Split inline bullets separated by bullet or middot chars into separate lines
    text = re.sub(r'\s*[\u2022\u00b7]\s*', '\n- ', text)

    # Replace any remaining leading bullet chars at line start
    text = re.sub(r'(?m)^[\s]*[\u2022\u00b7]\s*', '- ', text)

    # Ensure a blank line before bold headers e.g. **Possible Causes:**
    text = re.sub(r'(?<!\n)\n(\*\*[^\n]+\*\*)', r'\n\n\1', text)

    # Ensure each '- ' bullet starts on its own line
    text = re.sub(r'([^\n])(- )', r'\1\n\2', text)

    # Collapse 3+ consecutive newlines to 2
    text = re.sub(r'\n{3,}', '\n\n', text)

    return text.strip()


def _stream_and_fix(messages):
    """
    Yields chunks as they are generated by Ollama in real-time.
    """
    for chunk in llm.stream(messages):
        if chunk.content:
            yield str(chunk.content)


def stream_llm_answer(query: str, context: str):
    """
    RAG-grounded answer. Yields a cleanly formatted response from Llama3.
    """
    system_content = f"""You are an expert industrial maintenance assistant for a flour mill.
Answer ONLY using the provided context below.

FORMATTING RULES:
- Use clear markdown formatting.
- Each bullet point MUST be on its own separate line starting with '- '.
- Use **bold** for section headers.
- Enforce double newlines (blank lines) between section headers (e.g., before **Symptom:**, **Possible Causes:**, **Recommended Actions:**).
- NEVER put multiple section headers or bullet points on a single line.

ANSWER GUIDELINES:
- If the question is about troubleshooting a problem or fault, you MUST use this exact structure, keeping double newlines between sections:

  **Machine:** <machine name>

  **Symptom:** <symptom>

  **Possible Causes:**
  - cause one
  - cause two

  **Recommended Actions:**
  - action one
  - action two

- If the question is about specifications, procedures, design, or general information,
  answer naturally and directly using the context. Include relevant details like
  dimensions, temperatures, capacities, steps, etc.

Other rules:
- Do NOT invent dates, work orders, or personnel names.
- Do NOT fabricate information not present in the context.
- If the context does not contain the answer, reply exactly:
  "Not available in the provided maintenance data."
- Be technical, concise, and direct.

CONTEXT:
{context}
"""
    yield from _stream_and_fix([
        SystemMessage(content=system_content),
        HumanMessage(content=query),
    ])


def stream_llm_direct(query: str):
    """
    Direct LLM answer with no RAG context - for general questions and chat.
    """
    system_content = """You are a friendly and knowledgeable assistant specialising in
industrial flour mill equipment and maintenance.

FORMATTING RULES:
- Use clear markdown formatting.
- When listing items, put EACH item on its own line starting with '- '.
- Use **bold** for section headers.
- NEVER put multiple points on a single line.
- For greetings or small talk, respond naturally in plain prose (no bullet points needed).
"""
    yield from _stream_and_fix([
        SystemMessage(content=system_content),
        HumanMessage(content=query),
    ])
